<a href="https://colab.research.google.com/github/shifasafrinm/House_Price_Prediction/blob/main/RandomForest_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
import pandas as pd

In [6]:
df=pd.read_csv("/content/Heart_Disease_Prediction.csv")
df

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52,1,3,172,199,1,0,162,0,0.5,1,0,7,Absence
266,44,1,2,120,263,0,0,173,0,0.0,1,0,7,Absence
267,56,0,2,140,294,0,2,153,0,1.3,2,0,3,Absence
268,57,1,4,140,192,0,0,148,0,0.4,2,0,6,Absence
269,67,1,4,160,286,0,2,108,1,1.5,2,3,3,Presence

In [7]:
df.isnull().sum()

Age                        0
Sex                        0
Chest pain type            0
BP                         0
Cholesterol                0
FBS over 120               0
EKG results                0
Max HR                     0
Exercise angina            0
ST depression              0
Slope of ST                0
Number of vessels fluro    0
Thallium                   0
Heart Disease              0
dtype: int64

In [13]:
x=df[['Cholesterol','BP','Age','Chest pain type','Max HR']]
y=df['Heart Disease']

x_train ,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=24)

model=RandomForestClassifier()
model.fit(x_train,y_train)

predicted=model.predict(x_test)
print("Predicted :",predicted)
accuracy=accuracy_score(y_test,predicted)
print("Accuracy:",accuracy)
cm=confusion_matrix(y_test,predicted)
print("ConfusionMatrix:",cm)

Predicted : ['Absence' 'Presence' 'Absence' 'Absence' 'Absence' 'Absence' 'Presence'
 'Absence' 'Absence' 'Absence' 'Absence' 'Presence' 'Presence' 'Presence'
 'Presence' 'Presence' 'Absence' 'Absence' 'Absence' 'Absence' 'Presence'
 'Presence' 'Presence' 'Presence' 'Absence' 'Absence' 'Absence' 'Presence'
 'Presence' 'Presence' 'Presence' 'Presence' 'Absence' 'Presence'
 'Absence' 'Presence' 'Absence' 'Presence' 'Presence' 'Absence' 'Absence'
 'Presence' 'Absence' 'Absence' 'Absence' 'Absence' 'Absence' 'Absence'
 'Absence' 'Absence' 'Presence' 'Absence' 'Absence' 'Absence']
Accuracy: 0.6851851851851852
ConfusionMatrix: [[23  8]
 [ 9 14]]

In [16]:
x=df[['Cholesterol','BP','Age','Chest pain type','Max HR']]
y=df['Heart Disease']

x_train ,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=24)

model=RandomForestClassifier()
model.fit(x_train,y_train)

predicted=model.predict([[100,140,35,2,150]])
print("Predicted :",predicted)

Predicted : ['Absence']

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(